export const AUTH_START_REQUEST = "AUTH_START_REQUEST";
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS';
export const AUTH_SIGNIN_FAIL = 'AUTH_SIGNIN_FAIL';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL';
export const USER_LOGOUT = "USER_LOGOUT";

export const SELECTED_USER_PACKAGE = "SELECTED_USER_PACKAGE";
export const PACKAGES_GET_REQUEST = "PACKAGES_GET_REQUEST";
export const PACKAGES_GET_SUCCESS = "PACKAGES_GET_SUCCESS";
export const PACKAGES_GET_FAIL = "PACKAGES_GET_FAIL";

export const GET_SERVER_ERROR = "GET_SERVER_ERROR";

export const MAKE_PAYMENT_REQUEST = "MAKE_PAYMENT_REQUEST";
export const MAKE_PAYMENT_SUCCESS = "MAKE_PAYMENT_SUCCESS";
export const MAKE_PAYMENT_FAIL = "MAKE_PAYMENT_FAIL";

export const PLAY_SELECTED_VIDEO = "PLAY_SELECTED_VIDEO";
export const PLAY_SELECTED_AUDIO = "PLAY_SELECTED_AUDIO";

export const DOWNLOAD_VIDEO_REQUEST = "DOWNLOAD_VIDEO_REQUEST";
export const DOWNLOAD_VIDEO_SUCCESS = "DOWNLOAD_VIDEO_SUCCESS";
export const DOWNLOAD_VIDEO_FAIL = "DOWNLOAD_VIDEO_FAIL";

export const DOWNLOAD_AUDIO_REQUEST = "DOWNLOAD_AUDIO_REQUEST";
export const DOWNLOAD_AUDIO_SUCCESS = "DOWNLOAD_AUDIO_SUCCESS";
export const DOWNLOAD_AUDIO_FAIL = "DOWNLOAD_AUDIO_FAIL";

export const GET_VIDEOS_REQUEST = "GET_VIDEOS_REQUEST";
export const GET_VIDEOS_SUCCESS = "GET_VIDEOS_SUCCESS";
export const GET_VIDEOS_FAIL = "GET_VIDEOS_FAIL";

export const GET_AUDIOS_REQUEST = "GET_AUDIOS_REQUEST";
export const GET_AUDIOS_SUCCESS = "GET_AUDIOS_SUCCESS";
export const GET_AUDIOS_FAIL = "GET_AUDIOS_FAIL";

export const GET_DOWNLOADS_REQUEST = "GET_DOWNLOADS_REQUEST";
export const GET_DOWNLOADS_SUCCESS = "GET_DOWNLOADS_SUCCESS";
export const GET_DOWNLOADS_FAIL = "GET_DOWNLOADS_FAIL";

export const UPLOAD_AVATAR_REQUEST = "UPLOAD_AVATAR_REQUEST";
export const UPLOAD_AVATAR_SUCCESS = "UPLOAD_AVATAR_SUCCESS";
export const UPLOAD_AVATAR_FAIL = "UPLOAD_AVATAR_FAIL";