export const AUTH_START_REQUEST = "AUTH_START_REQUEST";
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS';
export const AUTH_SIGNIN_FAIL = 'AUTH_SIGNIN_FAIL';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL';

export const SELECTED_USER_PACKAGE = "SELECTED_USER_PACKAGE";
export const PACKAGES_GET_REQUEST = "PACKAGES_GET_REQUEST";
export const PACKAGES_GET_SUCCESS = "PACKAGES_GET_SUCCESS";
export const PACKAGES_GET_FAIL = "PACKAGES_GET_FAIL";

export const GET_SERVER_ERROR = "GET_SERVER_ERROR";

export const MAKE_PAYMENT_REQUEST = "MAKE_PAYMENT_REQUEST";
export const MAKE_PAYMENT_SUCCESS = "MAKE_PAYMENT_SUCCESS";
export const MAKE_PAYMENT_FAIL = "MAKE_PAYMENT_FAIL";